#server.port=9000
server:
  port: 9000
#server.servlet.context-path=/boot06
  servlet:
    context-path: /boot06
#view page prefix suffix setting
#spring.mvc.view.prefix=/WEB-INF/views/
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#spring.mvc.view.suffix=.jsp


